name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.18

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build -- --prod
      
    - name: Test
      run: npm run test -- --configuration=ci
